server:
  port: 8081
hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  connection:
    username: sa
    password: sa
    driver_class: org.h2.Driver
    url: jdbc:h2:mem:OtusExamplesDB;DB_CLOSE_DELAY=-1
  show_sql: true
  hbm2ddl:
    auto: validate

app:
    frontendServiceName: frontendService
    backendServiceName: backendService
