server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:OtusExamplesDB;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none

app:
    frontendServiceName: frontendService
    backendServiceName: backendService
logging:
  level:
    org:
      flywaydb: trace